- name: "Ansible para configurar VM"
  hosts: local
  gather_facts: False
  vars_files:
    - vars/aws_credentials.yml
    - vars/aws_vars.yml

  tasks:
    - name: Create iam user "{{ name_iam_user_s3 }}"
      iam_user:
        aws_access_key: "{{ AWS_access_key }}"
        aws_secret_key: "{{ AWS_secret_key }}"          
        name: "{{ name_iam_user_s3 }}-{{ item }}"       
        state: present
      register: iuser
      loop:
        - homolog
        - prod
    
    - name: Create iam group "{{ name_iam_user_s3 }}"
      iam_group:
        aws_access_key: "{{ AWS_access_key }}"
        aws_secret_key: "{{ AWS_secret_key }}"          
        name: "{{ name_grupo }}-group"        
        managed_policy:
          - arn:aws:iam::aws:policy/AmazonS3FullAccess
          - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
        state: present
        users:
          - "{{ name_iam_user_s3 }}-{{ item }}"
      loop:
        - homolog
        - prod
      register: addgroup

    - name: Get the current caller identity information
      aws_caller_info:
      register: caller_info  

    - name: "set fact: get account ID"
      set_fact:
        account_id: "{{ caller_info.account }}"
    
    - name: Create a buckets
      aws_s3:
        bucket: "{{ name_grupo }}-{{ item }}"
        mode: create
        region: "{{ region }}"
      loop:
        - homolog
        - prod

    - name: Create S3
      s3_bucket:
        aws_access_key: "{{ AWS_access_key }}"
        aws_secret_key: "{{ AWS_secret_key }}"          
        name: '{{ name_grupo }}-{{ item }}'
        region: "{{ region }}"
        state: present
        policy:
          Version: '2012-10-17'
          Statement: 
            - Effect: Allow
              Principal:
                  'AWS' : "arn:aws:iam::{{ account_id }}:user/{{ name_grupo }}-{{ item }}"
              Action: [
                  's3:ListBucket',
                  's3:DeleteObject',
                  's3:GetObject',
                  's3:PutObject',
                  's3:PutObjectAcl'
              ]
              Resource: [
                'arn:aws:s3:::{{ name_grupo }}-{{ item }}/*',
                'arn:aws:s3:::{{ name_grupo }}-{{ item }}'
              ]
      loop:
        - homolog
        - prod
